spring.application.name=Don Emiliano Backend

# General Settings
server.port=${API_PORT:4339}
server.servlet.context-path=/api/v1

spring.web.local=en

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.pool-name=HikariPool

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cache=DEBUG

# Security & CORS
security.cors.allowed-origins=http://localhost:4321
security.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
security.cors.allowed-headers=Authorization,Content-Type,Accept,Origin,X-Requested-With

spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=.
srping.devtools.restart.exclude=static/**,public/**,resources/**,META-INF/**
